service: shoppich-rest-api
provider:
 name: aws
 runtime: nodejs16.x
 memorySize: 128
 timeout: 300 # optional, in seconds, default is 6
 stage: dev
 versionFunctions: false
 region: ap-south-1
 
package:
  exclude:
    - node_modules/aws-sdk/**

functions:
 api:
   handler: lambda.handler
   events:
     - http: ANY /{proxy+}
     - http: ANY /

plugins:
 - serverless-offline
 